server:
  port: 8902
spring:
  application:
    name: alibaba-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: 192.168.71.128:1111 #通过nginx注册到 nacos集群

management:
  endpoints:
    web:
      exposure:
        include: "*"
