server:
  port: 80

spring:
  application:
    name: order-service
  #链路追踪和收集
  zipkin:
    base-url: http://192.168.71.128:9411
  sleuth:
    sampler:
      probability: 1 #相当于100%收集

eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/ # 入驻集群地址
      defaultZone: http://eureka7001.com:7001/eureka/
