server:
  port: 8401
spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        server-addr: 192.168.71.128:1111 #通过nginx注册到 nacos集群
    sentinel:
      transport:
        dashboard: localhost:8080 #sentinel dashboard地址
        port: 8719 #默认为8719端口，如果被占用会自动从8719开始一次+1，直到找到未被占用的端口
      #持久化 sentinel
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel-service
            groupId: DEFAULT_GROUP
            dataType: json
            ruleType: flow

management:
  endpoints:
    web:
      exposure:
        include: "*"
