server:
  port: 8021

spring:
  application:
    name: hystrix-turbine-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

turbine:
  app-config: PAYMENT-SERVICE
  cluster-name-expression: new String("default")